### ISSUE TITLE
Can u share the dataset in the original paper？ 您能分享一下原论文的数据吗

### ISSUE THREAD

**Issue by NonvolatileMemory** [stamdlee/DeepLearningFramework#1]

**Comment by aodongli** [comment]
Sorry the authors did not share their data. Please refer to Huawei for data. Thank you.

**Comment by NonvolatileMemory** [comment]
it seems they have published their dataset but the url didn't work
btw still very thank you

**Comment by carinazhang-meng** [comment]
在哪里可以看到他们发布的数据集呢，感谢

**Comment by carinazhang-meng** [comment]
Where could see their datasets?

**Comment by aodongli** [comment]
Thanks for asking. But I am not the author of their paper and do not have their data. I think emailing the authors would work.

Thanks,
Aodong
